language: clang

dist: trusty

sudo: true

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

r:
  - release

before_install:
  - sudo apt-get update || true
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN}; fi;

script:
  - make test
